In [1]:
w = [2, -3, -3]
x = [-1, -2]

# forward pass

In [4]:
dot = w[0]*x[0] + w[1]*x[1] + w[2]
print(dot)

1


In [7]:
import math 
f = 1.0 / (1.0 + math.exp(-dot))
print(f)

0.7310585786300049


# backward pass

In [8]:
ddot = (1-f) *f
print(ddot)

0.19661193324148185


In [10]:
dx = [w[0]*ddot, w[1]*ddot]
dw = [x[0] * ddot, x[1] * ddot, 1.0 * ddot]
print(dx, dw)

[0.3932238664829637, -0.5898357997244456] [-0.19661193324148185, -0.3932238664829637, 0.19661193324148185]


# staged computation
forward pass

In [13]:
x = 3 # example values
y = -4

sigy = 1.0 / (1.0 + math.exp(-y))
num = x + sigy
sigx = 1.0 / (1.0 + math.exp(-x))
suma = x + y
suma2 = suma**2
den = sigx + suma2
invden = 1 / den
f = num * invden

print(sigy, num, sigx, suma, suma2, den, invden,f)

0.01798620996209156 3.0179862099620918 0.9525741268224334 -1 1 1.9525741268224333 0.5121444488396316 1.5456448841066441


In [26]:
# backprop f = num * invden
dnum = invden # gradient on numerator                             #(8)
dinvden = num                                                     #(8)
# backprop invden = 1.0 / den 
dden = (-1.0 / (den**2)) * dinvden                                #(7)
# backprop den = sigx + suma2
dsigx = (1) * dden  
dsuma2 = (1) * dden                                               #(6)
# backprop xpysqr = xpy**2
dsuma = (2 * suma) * dsuma2                                         #(5)
# backprop xpy = x + y
dx = (1) * dsuma                                                   #(4)
dy = (1) * dsuma                                                   #(4)
# backprop sigx = 1.0 / (1 + math.exp(-x))
dx += ((1 - sigx) * sigx) * dsigx # Notice += !! See notes below  #(3)
# backprop num = x + sigy
dx += (1) * dnum                                                  #(2)
dsigy = (1) * dnum                                                #(2)
# backprop sigy = 1.0 / (1 + math.exp(-y))
dy += ((1 - sigy) * sigy) * dsigy                                 #(1)

print(dnum, dinvden, dden, dsigx, dsuma2, dsuma, dx, dy)

0.5121444488396316 3.0179862099620918 -0.7915934472725935 -0.7915934472725935 -0.7915934472725935 1.583186894545187 2.0595697955721652 1.5922327514838093


# Vectorized operations

In [30]:
import numpy as np

W = np.random.randn(5, 10) # 5x10
X = np.random.randn(10, 3) # 10x3
D = W.dot(X) # 5x3

print(D)

[[-7.53311766 -3.65599817  5.09826261]
 [ 1.5075009   2.09143959 -1.12701444]
 [ 1.17272786 -5.06407435  1.42023227]
 [ 2.00572066  0.77543769  2.58862275]
 [-3.21024316  1.29633621  1.00825081]]


In [31]:
print(np.arange(5))

[0 1 2 3 4]
